export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Header } from './header/Header'
export { default as Menu } from './menu/Menu'
export { default as Gallery } from './gallery/Gallery'